# Meta Data for SEO

## Homepage
title = "Уголок"
titleSeparator = "-"
titleAddition = "Тихое место для технической документации"
description = "Сервисы, книги, шпаргалки и инструкции."

## Open Graph
images = ["doks.png"]
ogLocale = "ru_RU"
domainTLD = "quizzical-archimedes-33b358.netlify.app"
titleHome = "Ugolok"

## Twitter Cards
twitterSite = "@ugolok"
twitterCreator = "@ugolok"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Ugolok"
schemaAuthor = "matero"
schemaAuthorTwitter = "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/h-enk"
schemaLocale = "ru-RU"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/ugolok"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/kiberlain/ugolok"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Сделано на генераторе статических сайтов <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>"
copyRight = "2021"

# Alert
alert = false
alertText = "Нравится? <a class=\"alert-link\" href=\"https://github.com/kiberlain/ugolok/stargazers\">звездочка на GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/kiberlain/ugolok"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  collapsibleSidebar = false
